<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color_swatch-option color</name>
   <tag></tag>
   <elementGuidId>eb259222-2973-4f9d-b8b6-0cf88e1fe942</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='narrow-by-list']/div[2]/div[2]/div/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.swatch-option-link-layered > div.swatch-option.color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Black&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53d2ce03-db85-4feb-a676-93f47207d1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color </value>
      <webElementGuid>b6326b22-765e-4aef-8d8b-06f64d8ec52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d1227559-724c-4227-971f-5cfe700d6950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7cc4208d-a884-4705-94df-b77b65c3bb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>49</value>
      <webElementGuid>911b72b8-a9b4-4b40-bb4f-c597d254f0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>Black</value>
      <webElementGuid>f0b69d96-3744-47da-91e8-5a79414e5119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>8faf2ad2-1c3f-4e57-811a-13004be2f51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;narrow-by-list&quot;)/div[@class=&quot;filter-options-item allow active&quot;]/div[@class=&quot;filter-options-content&quot;]/div[@class=&quot;swatch-attribute swatch-layered color&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]/a[@class=&quot;swatch-option-link-layered&quot;]/div[@class=&quot;swatch-option color&quot;]</value>
      <webElementGuid>c12250cd-1241-499e-b82b-518d69ee0ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='narrow-by-list']/div[2]/div[2]/div/div/a/div</value>
      <webElementGuid>f76e4199-c09a-48a6-a86a-c8e3039fed70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>9c01626d-1f0c-40ff-95dc-9c9fc1e0f9a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
