<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close</name>
   <tag></tag>
   <elementGuidId>46d0401c-5909-4ff5-b957-ccb81f807223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dismiss-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close ad&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1cfb5600-7f78-4014-bba2-6871de96f883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-0kvcn-e-14 button-common close-button milo-animation delay-4</value>
      <webElementGuid>6d9e8f14-307c-4911-b8ff-a1ed64056853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dismiss-button</value>
      <webElementGuid>2f85d2e6-e5f1-47cf-adec-4b1a2d125cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close ad</value>
      <webElementGuid>dc13df84-0ee2-4545-91df-f8f62fdb8fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e827448-9ab7-4978-8457-c12c5dd73856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7ba345c1-865e-4f95-9186-3d22ff646d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>14a46ad4-46dd-4e67-ba1d-5e28e5e3cbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)</value>
      <webElementGuid>c439ea60-43e6-4d8e-9856-a509b46ed60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Shopping Cart/iframe_Ad_ad_iframe</value>
      <webElementGuid>224a0e1e-4b43-446e-ae49-834c28aeacab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']</value>
      <webElementGuid>1caac1f3-32df-4852-aed4-fb0141c01b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='large-banner-rda-vanilla']/div/div[2]/div/div/div[3]</value>
      <webElementGuid>f17fe27f-ac0b-4062-9dad-ef9c49088afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sellernxt.com'])[1]/following::div[2]</value>
      <webElementGuid>66699e6a-8b44-4b71-b35a-3081dd155c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Scraping to Selling: Auto-Generate Amazon &amp;Shopify Listings. 100% Free eCommerce OS'])[1]/following::div[7]</value>
      <webElementGuid>0019c640-b89d-4d9b-b7bb-8b4794394fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::div[3]</value>
      <webElementGuid>057f4e94-938d-4b42-b341-1f042bbf488a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>da226551-c5ad-4575-ba1a-6b468a626f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dismiss-button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>5691a5e7-f500-4097-aaf2-2e4b493f7f90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
